# Generated by Django 3.2.7 on 2021-09-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
