# Generated by Django 3.2.7 on 2021-09-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_entrymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entries/%Y/%m/%d/'),
        ),
    ]
